import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors } from '../../utils';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.themeBackground,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: colors.Zypsii_color,
    paddingTop: Platform.OS === 'ios' ? 50 : 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  backButton: {
    marginRight: 16,
    padding: 4,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.white,
  },
  content: {
    flex: 1,
  },
  bannerContainer: {
    height: 220,
    width: '100%',
    position: 'relative',
    marginBottom: 8,
  },
  bannerImage: {
    width: '100%',
    height: '100%',
  },
  bannerGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 120,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  bannerPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.lightpink,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bannerPlaceholderText: {
    color: colors.fontMainColor,
    fontSize: 16,
    fontWeight: '500',
  },
  changeImageButton: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    backgroundColor: colors.Zypsii_color,
    padding: 12,
    borderRadius: 25,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  bannerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.white,
    textAlign: 'center',
  },
  sectionContainer: {
    padding: 20,
    backgroundColor: colors.white,
    marginBottom: 12,
    marginHorizontal: 16,
    borderRadius: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.fontMainColor,
    marginBottom: 20,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  defaultDateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lightpink,
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.Zypsii_color + '30',
  },
  defaultDateButtonText: {
    fontSize: 16,
    color: colors.Zypsii_color,
    fontWeight: '600',
    marginLeft: 8,
  },
  formGroup: {
    marginBottom: 20,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    color: colors.fontMainColor,
    marginBottom: 10,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1.5,
    borderColor: colors.grayLinesColor,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: colors.fontMainColor,
    backgroundColor: colors.white,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  pickerContainer: {
    borderWidth: 1.5,
    borderColor: colors.grayLinesColor,
    borderRadius: 12,
    backgroundColor: colors.white,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  picker: {
    height: 56,
  },
  dateInput: {
    borderWidth: 1.5,
    borderColor: colors.grayLinesColor,
    borderRadius: 12,
    padding: 16,
    backgroundColor: colors.white,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  updateButton: {
    backgroundColor: colors.Zypsii_color,
    padding: 18,
    borderRadius: 16,
    alignItems: 'center',
    margin: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  updateButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '700',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.grayLinesColor,
    borderRadius: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.white,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  inputIcon: {
    marginRight: 12,
  },
  locationInputContainer: {
    marginBottom: 16,
  },
  locationInput: {
    flex: 1,
    fontSize: 16,
    color: colors.fontMainColor,
    paddingVertical: 16,
    paddingHorizontal: 12,
  },
  locationAddress: {
    fontSize: 14,
    color: colors.fontSecondColor,
    marginTop: 6,
  },
  privacyContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  privacyButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.grayLinesColor,
    marginHorizontal: 6,
    alignItems: 'center',
    backgroundColor: colors.white,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  privacyButtonActive: {
    backgroundColor: colors.Zypsii_color,
    borderColor: colors.Zypsii_color,
    elevation: 2,
    shadowOpacity: 0.15,
  },
  privacyButtonText: {
    fontSize: 16,
    color: colors.fontMainColor,
    fontWeight: '500',
  },
  privacyButtonTextActive: {
    color: colors.white,
    fontWeight: '600',
  },
  dayCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.grayLinesColor,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  dayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  dayTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.fontMainColor,
  },
  dayDate: {
    fontSize: 14,
    color: colors.fontSecondColor,
    marginLeft: 12,
  },
  removeDayButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: colors.errorColor + '10',
  },
  mapButton: {
    backgroundColor: colors.Zypsii_color,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  mapButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  mapContainer: {
    height: 200,
    marginTop: 16,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.grayLinesColor,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  timeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  timeButton: {
    flex: 1,
    backgroundColor: colors.lightpink,
    padding: 16,
    borderRadius: 12,
    marginHorizontal: 6,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.Zypsii_color + '20',
  },
  timeText: {
    fontSize: 16,
    color: colors.fontMainColor,
    fontWeight: '500',
  },
  locationList: {
    marginTop: 16,
    padding: 16,
    backgroundColor: colors.lightpink,
    borderRadius: 12,
  },
  locationItem: {
    marginBottom: 12,
    padding: 16,
    backgroundColor: colors.white,
    borderRadius: 10,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  locationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  locationName: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.fontMainColor,
  },
  locationAddress: {
    fontSize: 14,
    color: colors.fontSecondColor,
    marginTop: 4,
  },
  locationDistance: {
    fontSize: 14,
    color: colors.Zypsii_color,
    marginTop: 6,
    fontWeight: '500',
  },
  miniMapContainer: {
    height: 100,
    borderRadius: 10,
    overflow: 'hidden',
    marginTop: 8,
  },
  miniMap: {
    flex: 1,
  },
  addLocationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
    borderWidth: 1,
    borderColor: colors.Zypsii_color + '30',
    borderStyle: 'dashed',
  },
  addLocationButtonText: {
    color: colors.Zypsii_color,
    marginLeft: 8,
    fontSize: 16,
    fontWeight: '600',
  },
  addDayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
    backgroundColor: colors.lightpink,
    borderWidth: 1,
    borderColor: colors.Zypsii_color + '30',
  },
  addDayButtonText: {
    color: colors.Zypsii_color,
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  datePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderWidth: 1.5,
    borderColor: colors.grayLinesColor,
    borderRadius: 12,
    backgroundColor: colors.white,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  timePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderWidth: 1.5,
    borderColor: colors.grayLinesColor,
    borderRadius: 12,
    backgroundColor: colors.white,
    marginTop: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  dateText: {
    fontSize: 16,
    color: colors.fontMainColor,
    fontWeight: '500',
  },
  timeText: {
    fontSize: 16,
    color: colors.fontMainColor,
    fontWeight: '500',
  },
  datePlaceholder: {
    color: colors.graycolor,
    fontWeight: '400',
  },
  timePlaceholder: {
    color: colors.graycolor,
    fontWeight: '400',
  },
  locationText: {
    fontSize: 16,
    color: colors.fontMainColor,
    paddingVertical: 16,
    fontWeight: '500',
  },
  updateDayButton: {
    backgroundColor: colors.Zypsii_color,
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  updateDayButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '700',
  },
}); 